### ISSUE TITLE
Add image history?

### ISSUE THREAD

**Issue by bsimmons123** [bsimmons123/YCP_Personalized_Commencement#46]
Allow the user to keep track of multiple images on their account? maybe a seperate table in the DB that just holds file names (one table for images and one for pictures) that are linked to the student's id

**Comment by robertwood68** [comment]
Potential enhancement but not necessary atm, might work on in class considering we're done the extremely difficult parts

**Comment by robertwood68** [comment]
So hear me out, what if we don't bother with this one now that we can just reset the content
